### ISSUE TITLE
Some questions about metrics

### ISSUE THREAD

**Issue by ScienceLi1125** [Friedrich-M/Instruct-4D-to-4D#6]
Hi Linzhan,
  Thank you for making your excellent code open source! 
  I wonder what ground truth images you use when evaluating metrics like PSNR, SSIM and LPIPS.
  I'm looking forward for your reply. Thanks!

**Comment by Friedrich-M** [comment]
Hi, thanks for your interest in our work. As mentioned in the main paper, we use the IP2P edited image as the pseudo-ground-truth to measure the editing quality with PSNR, SSIM, and LPIPS, since there are no existing evaluation metrics.

Besides, in my opinion, user study may be a better measurement for the editing task. You could also try it.

**Comment by ScienceLi1125** [comment]
Thank you for your instant reply! Your reply helps me a lot.
